better tool/pdfpng

diff --git a/tool/pdfpng b/tool/pdfpng
--- a/tool/pdfpng
+++ b/tool/pdfpng
@@ -1,18 +1,27 @@
 : ${PDFTOPPM=pdftoppm}
 : ${CONVERT=convert}
 
+if ! "$PDFTOPPM" -v >/dev/null 2>/dev/null
+then echo >&2 "[pdfpng] '$PDFTOPPM' failed"
+     exit 2
+fi
+
+if ! "$CONVERT" -version >/dev/null 2>/dev/null
+then echo >&2 "[pdfpng] '$CONVERT' failed"
+     exit 2
+fi
+
 f="$1"; shift
 d="$1"; shift
 
 t=/tmp/d.$$
 
 mkdir "$t"
-
-trap 'rm -f $t' 1 2 3 4 15
+trap 'rm -r $t; exit 2' 1 2 3 4 15
 
 "$PDFTOPPM" "$f" $t/i
 if test $? -ne 0
-then echo >&2 '[pdfpng] "$PDFTOPPM" faild'
+then echo >&2 '[pdfpng] "$PDFTOPPM" failed'
      exit 2
 fi
 
@@ -27,4 +36,4 @@ do b=`basename "$i" .ppm`
    fi
 done
 
-# rm -r "$t"
+rm -r "$t"
